export const MICROPHONE_THRESHOLD = -20;

export const START_TALKING_OFFSET = 500;

export const SILENT_RECORDING_PROGRESS_UPDATE_INTERVAL = 100;
export const RECORDING_PROGRESS_UPDATE_INTERVAL = 1000;
